# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AXh9isWjtNoKvnpncXtPUCi6683j6260
"""

print('Расчет площади и объема цилиндра')
print('____________________')
r=int(input('Введите значение радиуса: '))
h=int(input('Введите значение высоты: '))
print('--------------------')
print('Площадь цилиндра - ',3.14*r**2)
print('Обьем цилиндра - ',h*3.14*r**2)