# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jcc5Tit2FWG6YQRoGo-9083-WzAqiq3f
"""

print('Расчет площади круга')
print('____________________')
r=int(input('Введите значение радиуса: '))
print('--------------------')
print('Площадь круга - ',3.14*r**2)
print('Периметр круга - ',2*3.14*r)